;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_draw_brush_to_sprite
	.export		_draw_brush_left_hemisphere
	.export		_draw_brush_right_hemisphere
	.export		_draw_brush_lower_hemisphere
	.export		_draw_brush_upper_hemisphere
	.import		__draw_row_to_screen
	.import		__draw_row_to_sprite
	.import		__draw_column_to_sprite
	.import		_add_history_node_row
	.export		_row_widths
	.export		_brush_ptrs

.segment	"DATA"

_row_widths:
	.byte	$01
	.byte	$01
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$04
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$06
	.byte	$06
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$07
	.byte	$07
	.byte	$03
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$07
	.byte	$08
	.byte	$08
	.byte	$08
	.byte	$03
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$08
	.byte	$09
	.byte	$09
	.byte	$09
	.byte	$03
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$09
	.byte	$0a
	.byte	$0a
	.byte	$0a
	.byte	$04
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0a
	.byte	$0a
	.byte	$0b
	.byte	$0b
	.byte	$0b
	.byte	$0b
	.byte	$04
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0a
	.byte	$0b
	.byte	$0b
	.byte	$0c
	.byte	$0c
	.byte	$0c
	.byte	$0c
	.byte	$04
	.byte	$06
	.byte	$08
	.byte	$09
	.byte	$0a
	.byte	$0b
	.byte	$0b
	.byte	$0c
	.byte	$0c
	.byte	$0d
	.byte	$0d
	.byte	$0d
	.byte	$0d
	.byte	$04
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0a
	.byte	$0b
	.byte	$0c
	.byte	$0d
	.byte	$0d
	.byte	$0d
	.byte	$0e
	.byte	$0e
	.byte	$0e
	.byte	$0e
	.byte	$04
	.byte	$07
	.byte	$09
	.byte	$0a
	.byte	$0b
	.byte	$0c
	.byte	$0d
	.byte	$0d
	.byte	$0e
	.byte	$0e
	.byte	$0e
	.byte	$0f
	.byte	$0f
	.byte	$0f
	.byte	$0f
	.byte	$04
	.byte	$07
	.byte	$09
	.byte	$0a
	.byte	$0b
	.byte	$0c
	.byte	$0d
	.byte	$0e
	.byte	$0e
	.byte	$0f
	.byte	$0f
	.byte	$0f
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
_brush_ptrs:
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$03
	.byte	$06
	.byte	$0a
	.byte	$0f
	.byte	$15
	.byte	$1c
	.byte	$24
	.byte	$2d
	.byte	$37
	.byte	$42
	.byte	$4e
	.byte	$5b
	.byte	$69
	.byte	$78

; ---------------------------------------------------------------
; void __near__ draw_brush_to_sprite (unsigned char x, unsigned char y, unsigned char colour, unsigned char brush_size, unsigned char brush_type, unsigned char redraw_screen)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_to_sprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jne     L0002
	iny
	tax
	lda     (sp),y
	ina
	bne     L0003
	inx
L0003:	jsr     asrax1
	jsr     pusha
	lda     (sp)
	tay
	lda     _brush_ptrs,y
	jsr     pusha
	jsr     decsp3
	ldy     #$07
	lda     (sp),y
	and     #$01
	jsr     pusha
	lda     #$00
	ldy     #$02
L0024:	sta     (sp),y
	ldy     #$05
	cmp     (sp),y
	jcs     L0006
	dey
	lda     (sp),y
	tay
	lda     _row_widths,y
	ldy     #$03
	sta     (sp),y
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	lda     (sp)
	jeq     L000A
	dey
	lda     (sp),y
	asl     a
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	clc
	ldy     #$0C
	adc     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     _add_history_node_row
	ldy     #$03
	lda     (sp),y
	asl     a
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	clc
	ldy     #$0C
	adc     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	sec
	sbc     #$02
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     _add_history_node_row
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	asl     a
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	sec
	ldy     #$08
	sbc     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	asl     a
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	sec
	sbc     #$02
	jmp     L0023
L000A:	dey
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	clc
	ldy     #$0C
	adc     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     _add_history_node_row
	ldy     #$03
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	clc
	ldy     #$0C
	adc     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     _add_history_node_row
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	sec
	ldy     #$08
	sbc     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	clc
	ldy     #$0D
	adc     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	sec
	sbc     #$01
L0023:	jsr     __draw_row_to_sprite
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0024
L0006:	jsr     incsp6
	jmp     L000C
L0002:	jsr     decsp1
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ina
	bne     L000D
	inx
L000D:	jsr     asrax1
	jsr     pusha
	lda     #$00
	ldy     #$01
L0025:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L000F
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	sec
	ldy     #$01
	sbc     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$08
	adc     (sp),y
	sec
	ldy     #$02
	sbc     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _add_history_node_row
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	sec
	ldy     #$02
	sbc     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	clc
	ldy     #$09
	adc     (sp),y
	sec
	ldy     #$03
	sbc     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0025
L000F:	jsr     incsp2
L000C:	lda     (sp)
	beq     L0012
	jsr     decsp1
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ina
	bne     L0013
	inx
L0013:	jsr     asrax1
	jsr     pusha
	lda     #$00
	ldy     #$01
L0026:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L0015
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$06
	adc     (sp),y
	sec
	sbc     (sp)
	jsr     __draw_row_to_screen
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0026
L0015:	jsr     incsp2
L0012:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_left_hemisphere (unsigned char x, unsigned char y, unsigned char colour, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_left_hemisphere: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	lsr     a
	jsr     pusha
	lda     (sp)
	tay
	lda     _brush_ptrs,y
	jsr     pusha
	jsr     decsp3
	lda     #$00
	ldy     #$01
L0009:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L0004
	dey
	lda     (sp),y
	tay
	lda     _row_widths,y
	ldy     #$02
	sta     (sp),y
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$0B
	adc     (sp),y
	sec
	ldy     #$06
	sbc     (sp),y
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     __draw_column_to_sprite
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0009
L0004:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_right_hemisphere (unsigned char x, unsigned char y, unsigned char colour, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_right_hemisphere: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	lsr     a
	jsr     pusha
	lda     (sp)
	tay
	lda     _brush_ptrs,y
	jsr     pusha
	jsr     decsp3
	lda     #$00
	ldy     #$01
L0009:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L0004
	dey
	lda     (sp),y
	tay
	lda     _row_widths,y
	ldy     #$02
	sta     (sp),y
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	clc
	ldy     #$0B
	adc     (sp),y
	sec
	ldy     #$03
	sbc     (sp),y
	sec
	sbc     #$01
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	jsr     __draw_column_to_sprite
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0009
L0004:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_lower_hemisphere (unsigned char x, unsigned char y, unsigned char colour, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_lower_hemisphere: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	lsr     a
	jsr     pusha
	lda     (sp)
	tay
	lda     _brush_ptrs,y
	jsr     pusha
	jsr     decsp3
	lda     #$00
	ldy     #$01
L0009:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L0004
	dey
	lda     (sp),y
	tay
	lda     _row_widths,y
	ldy     #$02
	sta     (sp),y
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	clc
	ldy     #$0B
	adc     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	sec
	sbc     #$01
	jsr     __draw_row_to_sprite
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0009
L0004:	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_upper_hemisphere (unsigned char x, unsigned char y, unsigned char colour, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_upper_hemisphere: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	lsr     a
	jsr     pusha
	lda     (sp)
	tay
	lda     _brush_ptrs,y
	jsr     pusha
	jsr     decsp3
	lda     #$00
	ldy     #$01
L0009:	sta     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L0004
	dey
	lda     (sp),y
	tay
	lda     _row_widths,y
	ldy     #$02
	sta     (sp),y
	iny
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	clc
	ldy     #$0B
	adc     (sp),y
	sec
	ldy     #$07
	sbc     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0009
L0004:	ldy     #$0A
	jmp     addysp

.endproc

