;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__set_sprite_attribute
	.import		__set_sprite_address
	.export		_draw_pixel_to_sprite
	.export		_draw_brush_line
	.export		_draw_pixel_line
	.export		_draw_brush_circle
	.export		_tool_handler
	.export		_set_pal_icon_sprites
	.import		__primary_colour
	.import		__secondary_colour
	.import		__current_tool
	.import		_bmx_width
	.import		_bmx_height
	.import		_bmx_no_pals
	.import		__canvas_pow_scale
	.import		__square_root
	.import		__draw_canvas_to_screen
	.import		__draw_row_to_screen
	.import		__draw_row_to_sprite
	.import		__get_pixel
	.import		_add_history_node_position
	.import		_add_new_history_node
	.import		__mouse_data
	.import		_keycode
	.import		_draw_brush_to_sprite
	.export		_draw_pixel_line_h
	.export		_draw_pixel_line_v
	.export		_draw_brush_line_h
	.export		_draw_brush_line_v
	.export		_draw_brush_horizontal_line
	.export		_draw_brush_vertical_line
	.export		_mouse_addrs
	.export		_was_drawing_last_frame
	.export		_old_pix_x
	.export		_old_pix_y
	.export		_old_button
	.export		_brush_type
	.export		_brush_size
	.export		_fill_offset_arr_x
	.export		_fill_offset_arr_y
	.export		_flood_fill_queue_x
	.export		_flood_fill_queue_y
	.export		_queue_length
	.export		_selection_colour
	.export		_fill_colour
	.export		_abort_flood_fill
	.export		_flood_fill_pixel
	.export		_flood_fill
	.export		_line_brush_size
	.export		_line_brush_type
	.export		_point_selected
	.export		_previous_point_x
	.export		_previous_point_y
	.export		_line_draw_tool
	.export		_circle_brush_size
	.export		_circle_brush_type
	.export		_draw_circle_from_centre
	.export		_circle_draw_tool
	.export		_rect_brush_size
	.export		_rect_brush_type
	.export		_rectangle_draw_tool
	.export		_set_colour
	.export		_eye_dropper_tool
	.export		_handle_key_command
	.export		_get_pal_spr_pos_x
	.export		_get_pal_spr_pos_y
	.export		_palette_selection_handler

.segment	"DATA"

_mouse_addrs:
	.dword	$00016200
	.dword	$00016200
	.dword	$00016200
	.dword	$00016200
	.dword	$00016300
	.dword	$00016200
	.dword	$00016200
	.dword	$00016200
_was_drawing_last_frame:
	.byte	$00
_old_pix_x:
	.byte	$00
_old_pix_y:
	.byte	$00
_old_button:
	.byte	$00
_brush_type:
	.byte	$01
_brush_size:
	.byte	$02
_fill_offset_arr_x:
	.byte	$01
	.byte	$ff
	.byte	$ff
	.byte	$01
_fill_offset_arr_y:
	.byte	$00
	.byte	$01
	.byte	$ff
	.byte	$ff
_flood_fill_queue_x:
	.byte	$00
	.res	255,$00
_flood_fill_queue_y:
	.byte	$00
	.res	255,$00
_queue_length:
	.byte	$00
_abort_flood_fill:
	.byte	$00
_line_brush_size:
	.byte	$04
_line_brush_type:
	.byte	$01
_point_selected:
	.byte	$00
_circle_brush_size:
	.byte	$02
_circle_brush_type:
	.byte	$00
_draw_circle_from_centre:
	.byte	$01
_rect_brush_size:
	.byte	$02
_rect_brush_type:
	.byte	$00

.segment	"BSS"

_selection_colour:
	.res	1,$00
_fill_colour:
	.res	1,$00
_previous_point_x:
	.res	1,$00
_previous_point_y:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ draw_pixel_to_sprite (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_pixel_to_sprite: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	and     #$01
	beq     L0007
	lda     __primary_colour
	bra     L0008
L0007:	lda     __secondary_colour
L0008:	sta     (sp)
	lda     _was_drawing_last_frame
	beq     L0004
	lda     _old_pix_x
	jsr     pusha
	lda     _old_pix_y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	lda     _brush_size
	jsr     pusha
	lda     _brush_type
	jsr     _draw_brush_line
	bra     L0005
L0004:	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     _brush_size
	jsr     pusha
	lda     _brush_type
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
L0005:	lda     #$01
	sta     _was_drawing_last_frame
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_line (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_line: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$08
	lda     (sp),y
	ldy     #$06
	cmp     (sp),y
	bcc     L000B
	beq     L000B
	ldy     #$08
	lda     (sp),y
	sec
	ldy     #$06
	bra     L0010
L000B:	lda     (sp),y
	sec
	ldy     #$08
L0010:	sbc     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	ldy     #$05
	cmp     (sp),y
	bcc     L000D
	beq     L000D
	ldy     #$07
	lda     (sp),y
	sec
	ldy     #$05
	bra     L0011
L000D:	lda     (sp),y
	sec
	ldy     #$07
L0011:	sbc     (sp),y
	sta     (sp)
	ldy     #$01
	lda     (sp),y
	cmp     (sp)
	bcc     L0006
	beq     L0006
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _draw_brush_line_h
	bra     L0007
L0006:	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     _draw_brush_line_v
L0007:	ldy     #$09
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_pixel_line (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_pixel_line: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$06
	lda     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcc     L000B
	beq     L000B
	ldy     #$06
	lda     (sp),y
	sec
	ldy     #$04
	bra     L0010
L000B:	lda     (sp),y
	sec
	ldy     #$06
L0010:	sbc     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	ldy     #$03
	cmp     (sp),y
	bcc     L000D
	beq     L000D
	ldy     #$05
	lda     (sp),y
	sec
	ldy     #$03
	bra     L0011
L000D:	lda     (sp),y
	sec
	ldy     #$05
L0011:	sbc     (sp),y
	sta     (sp)
	ldy     #$01
	lda     (sp),y
	cmp     (sp)
	bcc     L0006
	beq     L0006
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_pixel_line_h
	jmp     incsp7
L0006:	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_pixel_line_v
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_circle (unsigned char cx, unsigned char cy, unsigned char radius, unsigned char col, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_circle: near

.segment	"CODE"

	jsr     pusha
	jsr     push0
	ldy     #$05
	lda     (sp),y
	jsr     negax
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     negax
	jsr     pushax
	jmp     L0004
L0002:	jsr     ldax0sp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0006
	eor     #$80
L0006:	bpl     L0005
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$03
	jsr     ldaxysp
	clc
	ldy     #$04
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	bra     L0016
L0005:	ldy     #$05
	jsr     ldaxysp
L0016:	jsr     aslax1
	ina
	bne     L0009
	inx
L0009:	jsr     addeq0sp
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$04
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$03
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$04
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$03
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$04
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$03
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$02
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$05
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$02
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$02
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sta     ptr1
	ldy     #$05
	lda     (sp),y
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$0B
	ldx     #$00
	lda     (sp),y
	sec
	ldy     #$02
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$05
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_to_sprite
	ldy     #$04
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L0004:	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	jsr     ldaxysp
	jsr     negax
	jsr     tosicmp
	jmi     L0002
	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ tool_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_tool_handler: near

.segment	"CODE"

	lda     __mouse_data
	ldx     __mouse_data+1
	jsr     pushax
	lda     __mouse_data+2
	ldx     __mouse_data+2+1
	jsr     pushax
	jsr     decsp2
	lda     __mouse_data+4
	jsr     pusha
	jsr     _handle_key_command
	ldy     #$06
	jsr     ldaxysp
	cmp     #$60
	txa
	sbc     #$00
	bcc     L0002
	ldy     #$06
	lda     (sp),y
	cmp     #$00
	bne     L0004
	dey
	lda     (sp),y
	cmp     #$E0
L0004:	bcs     L0002
	ldy     #$04
	jsr     ldaxysp
	cmp     #$28
	txa
	sbc     #$00
	bcc     L0002
	ldy     #$04
	lda     (sp),y
	cmp     #$00
	bne     L0005
	dey
	lda     (sp),y
	cmp     #$A8
L0005:	bcs     L0002
	ldx     #$00
	lda     __current_tool
	jsr     aslax2
	clc
	adc     #<(_mouse_addrs)
	tay
	txa
	adc     #>(_mouse_addrs)
	tax
	tya
	jsr     ldeaxi
	jsr     shreax4
	jsr     shreax1
	jsr     pusheax
	lda     #$00
	ldx     #$80
	jsr     tosadd0ax
	jsr     pushax
	lda     #$00
	bra     L002A
L0002:	ldx     #$8B
	lda     #$00
	jsr     pushax
L002A:	jsr     __set_sprite_address
	lda     (sp)
	and     #$01
	bne     L002E
	lda     (sp)
	and     #$02
	jeq     L0009
L002E:	ldy     #$06
	jsr     ldaxysp
	cmp     #$60
	txa
	sbc     #$00
	jcc     L000C
	ldy     #$06
	lda     (sp),y
	cmp     #$00
	bne     L000E
	dey
	lda     (sp),y
	cmp     #$E0
L000E:	jcs     L000C
	ldy     #$04
	jsr     ldaxysp
	cmp     #$28
	txa
	sbc     #$00
	jcc     L000C
	ldy     #$04
	lda     (sp),y
	cmp     #$00
	bne     L000F
	dey
	lda     (sp),y
	cmp     #$A8
L000F:	jcs     L000C
	ldx     #$00
	lda     #$60
	ldy     #$05
	jsr     subeqysp
	ldx     #$00
	lda     #$28
	ldy     #$03
	jsr     subeqysp
	ldy     #$06
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$04
	sec
	sbc     __canvas_pow_scale
	tay
	lda     ptr1
	ldx     ptr1+1
	jsr     shraxy
	ldy     #$02
	sta     (sp),y
	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$04
	sec
	sbc     __canvas_pow_scale
	tay
	lda     ptr1
	ldx     ptr1+1
	jsr     shraxy
	ldy     #$01
	sta     (sp),y
	lda     _old_pix_x
	iny
	cmp     (sp),y
	bne     L0032
	lda     _old_pix_y
	dey
	cmp     (sp),y
	bne     L0032
	lda     _old_button
	cmp     (sp)
	jeq     L001F
L0032:	lda     __current_tool
	bne     L0033
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _draw_pixel_to_sprite
	jmp     L001F
L0033:	lda     __current_tool
	cmp     #$01
	bne     L0034
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _flood_fill
	bra     L001F
L0034:	lda     __current_tool
	cmp     #$03
	bne     L0035
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _line_draw_tool
	bra     L001F
L0035:	lda     __current_tool
	cmp     #$04
	bne     L0036
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _eye_dropper_tool
	bra     L001F
L0036:	lda     __current_tool
	cmp     #$07
	bne     L0037
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _rectangle_draw_tool
	bra     L001F
L0037:	lda     __current_tool
	cmp     #$06
	bne     L001F
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _circle_draw_tool
L001F:	ldy     #$02
	lda     (sp),y
	sta     _old_pix_x
	dey
	lda     (sp),y
	sta     _old_pix_y
	bra     L0028
L000C:	lda     _was_drawing_last_frame
	beq     L0039
	jsr     _add_new_history_node
L0039:	stz     _was_drawing_last_frame
	ldy     #$06
	jsr     ldaxysp
	cmp     #$F0
	txa
	sbc     #$00
	bcc     L0028
	ldy     #$06
	lda     (sp),y
	cmp     #$01
	bne     L0024
	dey
	lda     (sp),y
	cmp     #$30
L0024:	bcs     L0028
	ldy     #$04
	jsr     ldaxysp
	cmp     #$60
	txa
	sbc     #$00
	bcc     L0028
	ldy     #$04
	lda     (sp),y
	cmp     #$00
	bne     L0025
	dey
	lda     (sp),y
	cmp     #$E0
L0025:	bcs     L0028
	ldy     #$08
	jsr     pushwysp
	ldy     #$08
	jsr     pushwysp
	ldy     #$04
	lda     (sp),y
	jsr     _palette_selection_handler
	bra     L0028
L0009:	lda     _was_drawing_last_frame
	beq     L003E
	jsr     _add_new_history_node
L003E:	stz     _was_drawing_last_frame
L0028:	lda     (sp)
	sta     _old_button
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ set_pal_icon_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_pal_icon_sprites: near

.segment	"CODE"

	lda     #$05
	jsr     pusha
	ldx     #$0B
	lda     #$28
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     __primary_colour
	jsr     _get_pal_spr_pos_x
	jsr     pushax
	lda     __primary_colour
	jsr     _get_pal_spr_pos_y
	jsr     pushax
	lda     #$0C
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$0F
	jsr     __set_sprite_attribute
	lda     #$06
	jsr     pusha
	ldx     #$0B
	lda     #$29
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     __secondary_colour
	jsr     _get_pal_spr_pos_x
	clc
	adc     $005A
	bcc     L0002
	inx
L0002:	jsr     decax8
	jsr     pushax
	lda     __secondary_colour
	jsr     _get_pal_spr_pos_y
	clc
	adc     $005B
	bcc     L0003
	inx
L0003:	jsr     decax8
	jsr     pushax
	lda     #$0C
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$0F
	jmp     __set_sprite_attribute

.endproc

; ---------------------------------------------------------------
; void __near__ draw_pixel_line_h (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_pixel_line_h: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	lda     #$00
	jsr     pusha
	jsr     decsp2
	lda     #$00
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	ldy     #$0A
	cmp     (sp),y
	bcc     L0013
	beq     L0013
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	ldy     #$0D
	sta     (sp),y
	lda     (sp)
	ldy     #$0B
	sta     (sp),y
	iny
	lda     (sp),y
	sta     (sp)
	ldy     #$0A
	lda     (sp),y
	ldy     #$0C
	sta     (sp),y
	lda     (sp)
	ldy     #$0A
	sta     (sp),y
	jsr     incsp1
L0013:	lda     (sp),y
	sec
	ldy     #$0C
	sbc     (sp),y
	ldy     #$07
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	sec
	ldy     #$0B
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	ldy     #$09
	cmp     (sp),y
	bcc     L0003
	beq     L0003
	lda     #$01
	ldy     #$03
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$09
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
L0003:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000C
	inx
L000C:	sec
	iny
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	tax
	pla
	ldy     #$04
	jsr     staxysp
	ldy     #$0C
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	ldy     #$0C
	lda     (sp),y
	ldy     #$01
L0010:	sta     (sp),y
	ldy     #$0A
	cmp     (sp),y
	beq     L0011
	jcs     L0005
L0011:	clc
	lda     #$01
	adc     (sp)
	sta     (sp)
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	jsr     _add_history_node_position
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$02
	lda     (sp),y
	jsr     __draw_row_to_screen
	ldy     #$05
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
	ldy     #$03
	lda     (sp),y
	beq     L000A
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bra     L000F
L000A:	dey
	clc
	ina
	adc     (sp),y
L000F:	sta     (sp),y
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000D
	inx
L000D:	ldy     #$04
	jsr     subeqysp
	lda     #$00
	sta     (sp)
L0008:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000E
	inx
L000E:	ldy     #$04
	jsr     addeqysp
	ldy     #$01
	clc
	tya
	adc     (sp),y
	jmp     L0010
L0005:	ldy     #$02
	lda     (sp),y
	jsr     __draw_row_to_screen
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_pixel_line_v (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_pixel_line_v: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	lda     #$00
	jsr     pusha
	jsr     decsp2
	ldy     #$0A
	lda     (sp),y
	ldy     #$08
	cmp     (sp),y
	bcc     L0002
	beq     L0002
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$0A
	lda     (sp),y
	ldy     #$0C
	sta     (sp),y
	lda     (sp)
	ldy     #$0A
	sta     (sp),y
	iny
	lda     (sp),y
	sta     (sp)
	ldy     #$09
	lda     (sp),y
	ldy     #$0B
	sta     (sp),y
	lda     (sp)
	ldy     #$09
	sta     (sp),y
	jsr     incsp1
L0002:	ldy     #$09
	lda     (sp),y
	sec
	ldy     #$0B
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
	ldy     #$08
	lda     (sp),y
	sec
	ldy     #$0A
	sbc     (sp),y
	ldy     #$05
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	ldy     #$09
	cmp     (sp),y
	bcc     L0003
	beq     L0003
	lda     #$01
	ldy     #$02
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$09
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
L0003:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000C
	inx
L000C:	sec
	dey
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	tax
	pla
	ldy     #$03
	jsr     staxysp
	ldy     #$0B
	lda     (sp),y
	sta     (sp)
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	ldy     #$01
L0010:	sta     (sp),y
	ldy     #$08
	cmp     (sp),y
	beq     L0011
	jcs     L0005
L0011:	lda     (sp)
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _add_history_node_position
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     __draw_row_to_sprite
	ldy     #$01
	lda     (sp),y
	jsr     __draw_row_to_screen
	ldy     #$04
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
	ldy     #$02
	lda     (sp),y
	beq     L000A
	lda     (sp)
	sec
	sbc     #$01
	bra     L000F
L000A:	clc
	ina
	adc     (sp)
L000F:	sta     (sp)
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000D
	inx
L000D:	ldy     #$03
	jsr     subeqysp
L0008:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L000E
	inx
L000E:	ldy     #$03
	jsr     addeqysp
	ldy     #$01
	clc
	tya
	adc     (sp),y
	jmp     L0010
L0005:	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_line_h (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_line_h: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	lda     #$00
	jsr     pusha
	jsr     decsp3
	ldy     #$0E
	lda     (sp),y
	ldy     #$0C
	cmp     (sp),y
	bcc     L0002
	beq     L0002
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	ldy     #$0F
	sta     (sp),y
	lda     (sp)
	ldy     #$0D
	sta     (sp),y
	iny
	lda     (sp),y
	sta     (sp)
	ldy     #$0C
	lda     (sp),y
	ldy     #$0E
	sta     (sp),y
	lda     (sp)
	ldy     #$0C
	sta     (sp),y
	jsr     incsp1
L0002:	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$0E
	sbc     (sp),y
	ldy     #$07
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$0D
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	ldy     #$0B
	cmp     (sp),y
	bcc     L0003
	beq     L0003
	lda     #$01
	ldy     #$03
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	sec
	ldy     #$0B
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
L0003:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0016
	inx
L0016:	sec
	iny
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	tax
	pla
	ldy     #$04
	jsr     staxysp
	ldy     #$0E
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	ldy     #$0E
	lda     (sp),y
	ldy     #$01
L001E:	sta     (sp),y
	ldy     #$0C
	cmp     (sp),y
	beq     L0021
	bcs     L0023
L0021:	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	ldy     #$05
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
	ldy     #$03
	lda     (sp),y
	beq     L000A
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bra     L001D
L000A:	dey
	clc
	ina
	adc     (sp),y
L001D:	sta     (sp),y
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0017
	inx
L0017:	ldy     #$04
	jsr     subeqysp
L0008:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0018
	inx
L0018:	ldy     #$04
	jsr     addeqysp
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L001E
L0023:	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	ldy     #$03
	lda     (sp),y
	beq     L0020
	lda     #$00
L001F:	sta     (sp)
	lda     (sp)
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	clc
	ldy     #$08
	adc     (sp),y
	bcc     L0019
	inx
L0019:	jsr     incax2
	jsr     tosicmp
	bpl     L0013
	ldy     #$0B
	lda     (sp),y
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	lsr     a
	jsr     tossuba0
	sta     ptr1
	lda     (sp)
	clc
	adc     ptr1
	sec
	sbc     #$01
	jsr     __draw_row_to_screen
	clc
	lda     #$01
	adc     (sp)
	bra     L001F
L0020:	sta     (sp)
	lda     (sp)
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	clc
	ldy     #$08
	adc     (sp),y
	bcc     L001B
	inx
L001B:	jsr     incax2
	jsr     tosicmp
	bpl     L0013
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	lsr     a
	jsr     tossuba0
	sta     ptr1
	lda     (sp)
	clc
	adc     ptr1
	sec
	sbc     #$01
	jsr     __draw_row_to_screen
	clc
	lda     #$01
	adc     (sp)
	bra     L0020
L0013:	ldy     #$0F
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_line_v (unsigned char x0, unsigned char y0, unsigned char x1, unsigned char y1, unsigned char col, unsigned char brush_size, unsigned char brush_type)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_line_v: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	lda     #$00
	jsr     pusha
	jsr     decsp3
	ldy     #$0D
	lda     (sp),y
	ldy     #$0B
	cmp     (sp),y
	bcc     L0002
	beq     L0002
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0D
	lda     (sp),y
	ldy     #$0F
	sta     (sp),y
	lda     (sp)
	ldy     #$0D
	sta     (sp),y
	iny
	lda     (sp),y
	sta     (sp)
	ldy     #$0C
	lda     (sp),y
	ldy     #$0E
	sta     (sp),y
	lda     (sp)
	ldy     #$0C
	sta     (sp),y
	jsr     incsp1
L0002:	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0E
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	ldy     #$0C
	lda     (sp),y
	sec
	ldy     #$0E
	sbc     (sp),y
	ldy     #$07
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	sec
	ldy     #$0D
	sbc     (sp),y
	ldy     #$06
	sta     (sp),y
	ldy     #$0E
	lda     (sp),y
	ldy     #$0C
	cmp     (sp),y
	bcc     L0003
	beq     L0003
	lda     #$01
	ldy     #$03
	sta     (sp),y
	ldy     #$0E
	lda     (sp),y
	sec
	ldy     #$0C
	sbc     (sp),y
	ldy     #$07
	sta     (sp),y
L0003:	ldy     #$07
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0010
	inx
L0010:	sec
	dey
	sbc     (sp),y
	pha
	txa
	sbc     #$00
	tax
	pla
	ldy     #$04
	jsr     staxysp
	ldy     #$0E
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	ldy     #$0D
	lda     (sp),y
	ldy     #$02
L0016:	sta     (sp),y
	ldy     #$0B
	cmp     (sp),y
	beq     L0018
	bcs     L0005
L0018:	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	ldy     #$05
	jsr     ldaxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0009
	eor     #$80
L0009:	bpl     L0008
	ldy     #$03
	lda     (sp),y
	beq     L000A
	ldy     #$01
	lda     (sp),y
	sec
	sbc     #$01
	bra     L0015
L000A:	ldy     #$01
	clc
	tya
	adc     (sp),y
L0015:	sta     (sp),y
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0011
	inx
L0011:	ldy     #$04
	jsr     subeqysp
L0008:	ldy     #$07
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L0012
	inx
L0012:	ldy     #$04
	jsr     addeqysp
	ldy     #$02
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0016
L0005:	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	ldy     #$0C
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_to_sprite
	lda     #$00
L0017:	sta     (sp)
	lda     (sp)
	jsr     pusha0
	ldy     #$08
	lda     (sp),y
	clc
	ldy     #$0B
	adc     (sp),y
	bcc     L0013
	inx
L0013:	jsr     incax2
	jsr     tosicmp
	bpl     L000D
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	ldy     #$0B
	lda     (sp),y
	lsr     a
	jsr     tossuba0
	sta     ptr1
	lda     (sp)
	clc
	adc     ptr1
	sec
	sbc     #$01
	jsr     __draw_row_to_screen
	clc
	lda     #$01
	adc     (sp)
	bra     L0017
L000D:	ldy     #$0F
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_horizontal_line (unsigned char x, unsigned char y, unsigned char width, unsigned char col, unsigned char brush_size, unsigned char brush_type, unsigned char redraw)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_horizontal_line: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
L0007:	sta     (sp)
	ldy     #$05
	cmp     (sp),y
	bcs     L0003
	lda     (sp)
	clc
	ldy     #$07
	adc     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_brush_to_sprite
	clc
	lda     #$01
	adc     (sp)
	bra     L0007
L0003:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ draw_brush_vertical_line (unsigned char x, unsigned char y, unsigned char height, unsigned char col, unsigned char brush_size, unsigned char brush_type, unsigned char redraw)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_brush_vertical_line: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
L0007:	sta     (sp)
	ldy     #$05
	cmp     (sp),y
	bcs     L0003
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	ldy     #$07
	adc     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_brush_to_sprite
	clc
	lda     #$01
	adc     (sp)
	bra     L0007
L0003:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ flood_fill_pixel (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_flood_fill_pixel: near

.segment	"CODE"

	jsr     decsp1
	lda     #<(_flood_fill_queue_x)
	ldx     #>(_flood_fill_queue_x)
	clc
	adc     _queue_length
	bcc     L0002
	inx
L0002:	ldy     #$00
	jsr     ldaidx
	jsr     pusha
	lda     #<(_flood_fill_queue_y)
	ldx     #>(_flood_fill_queue_y)
	clc
	adc     _queue_length
	bcc     L0003
	inx
L0003:	ldy     #$00
	jsr     ldaidx
	jsr     pusha
	jsr     decsp1
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     _fill_colour
	jsr     _add_history_node_position
	lda     _fill_colour
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     __draw_row_to_sprite
	lda     #$00
	ldy     #$03
L001C:	sta     (sp),y
	cmp     #$04
	jcs     L0005
	lda     #<(_fill_offset_arr_x)
	ldx     #>(_fill_offset_arr_x)
	clc
	adc     (sp),y
	bcc     L0008
	inx
L0008:	ldy     #$00
	jsr     ldaidx
	cmp     #$80
	ldy     #$02
	clc
	adc     (sp),y
	sta     (sp),y
	lda     #<(_fill_offset_arr_y)
	ldx     #>(_fill_offset_arr_y)
	iny
	clc
	adc     (sp),y
	bcc     L000B
	inx
L000B:	ldy     #$00
	jsr     ldaidx
	cmp     #$80
	iny
	clc
	adc     (sp),y
	sta     (sp),y
	iny
	lda     (sp),y
	tax
	jmi     L0006
	ldx     #$00
	lda     (sp),y
	bpl     L0011
	dex
L0011:	jsr     pushax
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     tosicmp
	bcs     L0006
	ldy     #$01
	lda     (sp),y
	tax
	bmi     L0006
	ldx     #$00
	lda     (sp),y
	bpl     L0013
	dex
L0013:	jsr     pushax
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     ldaxi
	jsr     tosicmp
	bcs     L0006
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     __get_pixel
	sta     (sp)
	cmp     _selection_colour
	bne     L0006
	lda     #<(_flood_fill_queue_x)
	ldx     #>(_flood_fill_queue_x)
	clc
	adc     _queue_length
	bcc     L0017
	inx
L0017:	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	lda     #<(_flood_fill_queue_y)
	ldx     #>(_flood_fill_queue_y)
	clc
	adc     _queue_length
	bcc     L0019
	inx
L0019:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (sp),y
	sta     (ptr1)
	inc     _queue_length
	lda     _queue_length
	cmp     #$FF
	bne     L0006
	sty     _abort_flood_fill
L0006:	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	jmp     L001C
L0005:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ flood_fill (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_flood_fill: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     __get_pixel
	sta     _selection_colour
	stz     _queue_length
	lda     (sp)
	and     #$01
	beq     L000E
	lda     __primary_colour
	bra     L000D
L000E:	lda     __secondary_colour
L000D:	sta     _fill_colour
	cmp     _selection_colour
	beq     L0001
	lda     #<(_flood_fill_queue_x)
	ldx     #>(_flood_fill_queue_x)
	clc
	adc     _queue_length
	bcc     L0005
	inx
L0005:	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	lda     #<(_flood_fill_queue_y)
	ldx     #>(_flood_fill_queue_y)
	clc
	adc     _queue_length
	bcc     L0007
	inx
L0007:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (sp),y
	sta     (ptr1)
	inc     _queue_length
	bra     L0010
L000F:	dec     _queue_length
	jsr     _flood_fill_pixel
	lda     _abort_flood_fill
	beq     L0010
	stz     _abort_flood_fill
	bra     L000A
L0010:	lda     _queue_length
	bne     L000F
L000A:	jsr     _add_new_history_node
	jsr     __draw_canvas_to_screen
L0001:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ line_draw_tool (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_line_draw_tool: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	and     #$01
	beq     L0007
	lda     __primary_colour
	bra     L0009
L0007:	lda     __secondary_colour
L0009:	sta     (sp)
	lda     _point_selected
	bne     L0008
	sty     _point_selected
	ldy     #$03
	lda     (sp),y
	sta     _previous_point_x
	dey
	lda     (sp),y
	sta     _previous_point_y
	jmp     incsp4
L0008:	stz     _point_selected
	lda     _previous_point_x
	jsr     pusha
	lda     _previous_point_y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	lda     _line_brush_size
	jsr     pusha
	lda     _line_brush_type
	jsr     _draw_brush_line
	jsr     _add_new_history_node
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ circle_draw_tool (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_circle_draw_tool: near

.segment	"CODE"

	jsr     pusha
	lda     _point_selected
	bne     L0002
	ina
	sta     _point_selected
	ldy     #$02
	lda     (sp),y
	sta     _previous_point_x
	dey
	lda     (sp),y
	sta     _previous_point_y
	jmp     incsp3
L0002:	ldy     #$0A
	jsr     subysp
	stz     _point_selected
	ldy     #$0A
	lda     (sp),y
	and     #$01
	beq     L0016
	lda     __primary_colour
	bra     L001A
L0016:	lda     __secondary_colour
L001A:	ldy     #$02
	sta     (sp),y
	ldy     #$0C
	lda     (sp),y
	cmp     _previous_point_x
	bcc     L0017
	beq     L0017
	sec
	sbc     _previous_point_x
	ldx     #$00
	bcs     L000C
	dex
L000C:	ldy     #$08
	jsr     staxysp
	lda     _previous_point_x
	bra     L001B
L0017:	lda     _previous_point_x
	sec
	sbc     (sp),y
	ldx     #$00
	bcs     L000D
	dex
L000D:	ldy     #$08
	jsr     staxysp
	ldy     #$0C
	lda     (sp),y
L001B:	ldy     #$01
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	cmp     _previous_point_y
	bcc     L0018
	beq     L0018
	sec
	sbc     _previous_point_y
	ldx     #$00
	bcs     L000E
	dex
L000E:	ldy     #$06
	jsr     staxysp
	lda     _previous_point_y
	bra     L001C
L0018:	lda     _previous_point_y
	sec
	sbc     (sp),y
	ldx     #$00
	bcs     L000F
	dex
L000F:	ldy     #$06
	jsr     staxysp
	ldy     #$0B
	lda     (sp),y
L001C:	sta     (sp)
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     tosumulax
	jsr     pushax
	ldy     #$0B
	jsr     pushwysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     tosumulax
	jsr     tosaddax
	ldy     #$04
	jsr     staxysp
	jsr     __square_root
	ldy     #$03
	sta     (sp),y
	lda     _draw_circle_from_centre
	beq     L0019
	lda     _previous_point_x
	jsr     pusha
	lda     _previous_point_y
	bra     L0026
L0019:	lda     (sp),y
	lsr     a
	sta     (sp),y
	ldy     #$01
	lda     (sp),y
	sta     ptr1
	ldy     #$09
	jsr     ldaxysp
	jsr     shrax1
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	sta     ptr1
	ldy     #$08
	jsr     ldaxysp
	jsr     shrax1
	clc
	adc     ptr1
L0026:	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	lda     _circle_brush_size
	jsr     pusha
	lda     _circle_brush_type
	jsr     _draw_brush_circle
	ldy     #$0A
	jsr     addysp
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ rectangle_draw_tool (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rectangle_draw_tool: near

.segment	"CODE"

	jsr     pusha
	lda     _point_selected
	bne     L0002
	ina
	sta     _point_selected
	ldy     #$02
	lda     (sp),y
	sta     _previous_point_x
	dey
	lda     (sp),y
	sta     _previous_point_y
	jmp     incsp3
L0002:	jsr     decsp1
	ldy     #$01
	lda     (sp),y
	and     #$01
	beq     L001D
	lda     __primary_colour
	bra     L0021
L001D:	lda     __secondary_colour
L0021:	sta     (sp)
	stz     _point_selected
	lda     _previous_point_x
	ldy     #$03
	cmp     (sp),y
	bcs     L001F
	lda     _previous_point_x
	jsr     pusha
	lda     _previous_point_y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	sec
	sbc     _previous_point_x
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_horizontal_line
	lda     _previous_point_x
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	sec
	sbc     _previous_point_x
	bra     L0034
L001F:	lda     (sp),y
	jsr     pusha
	lda     _previous_point_y
	jsr     pusha
	lda     _previous_point_x
	sec
	ldy     #$05
	sbc     (sp),y
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_horizontal_line
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _previous_point_x
	sec
	ldy     #$05
	sbc     (sp),y
L0034:	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_horizontal_line
	lda     _previous_point_y
	ldy     #$02
	cmp     (sp),y
	bcs     L0020
	lda     _previous_point_x
	jsr     pusha
	lda     _previous_point_y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	sec
	sbc     _previous_point_y
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_vertical_line
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _previous_point_y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	sec
	sbc     _previous_point_y
	bra     L0035
L0020:	lda     _previous_point_x
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _previous_point_y
	sec
	ldy     #$04
	sbc     (sp),y
	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$00
	jsr     _draw_brush_vertical_line
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _previous_point_y
	sec
	ldy     #$04
	sbc     (sp),y
L0035:	ina
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     _rect_brush_size
	jsr     pusha
	lda     _rect_brush_type
	jsr     pusha
	lda     #$01
	jsr     _draw_brush_vertical_line
	jsr     _add_new_history_node
	jsr     incsp1
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ set_colour (unsigned char *addr, unsigned char new_col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_colour: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	sta     (ptr1)
	jsr     _set_pal_icon_sprites
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ eye_dropper_tool (unsigned char pix_x, unsigned char pix_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_eye_dropper_tool: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     __get_pixel
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	and     #$01
	beq     L0002
	lda     #<(__primary_colour)
	ldx     #>(__primary_colour)
	bra     L0007
L0002:	lda     #<(__secondary_colour)
	ldx     #>(__secondary_colour)
L0007:	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     _set_colour
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ handle_key_command (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_key_command: near

.segment	"CODE"

	lda     _keycode
	beq     L0002
	lda     __current_tool
	cmp     #$03
	bne     L0014
	lda     _keycode
	cmp     #$1B
	bne     L0019
	stz     _point_selected
	bra     L0019
L0014:	lda     __current_tool
	cmp     #$07
	bne     L0015
	lda     _keycode
	cmp     #$1B
	bne     L0019
	stz     _point_selected
	bra     L0019
L0015:	lda     __current_tool
	bne     L0019
	lda     _keycode
	cmp     #$3D
	bne     L0016
	lda     #$02
	clc
	adc     _brush_size
	sta     _brush_size
	cmp     #$21
	bcc     L0019
	lda     #$20
	sta     _brush_size
	bra     L0019
L0016:	lda     _keycode
	cmp     #$2D
	bne     L0017
	lda     _brush_size
	sec
	sbc     #$02
	sta     _brush_size
	cmp     #$02
	bcs     L0019
	lda     #$02
	sta     _brush_size
	bra     L0019
L0017:	lda     _keycode
	cmp     #$51
	bne     L0018
	lda     #$00
	bra     L0013
L0018:	lda     _keycode
	cmp     #$57
	bne     L0019
	lda     #$01
L0013:	sta     _brush_type
L0019:	lda     _keycode
	sta     $0060
L0002:	rts

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ get_pal_spr_pos_x (unsigned char colour)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_pal_spr_pos_x: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     $0059
	jsr     tosumoda0
	jsr     pushax
	lda     $005A
	jsr     tosmula0
	jsr     stax0sp
	ldx     #$00
	lda     #$F0
	jsr     addeq0sp
	jsr     ldax0sp
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ get_pal_spr_pos_y (unsigned char colour)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_pal_spr_pos_y: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     $0059
	jsr     tosudiva0
	jsr     pushax
	lda     $005B
	jsr     tosmula0
	jsr     stax0sp
	ldx     #$00
	lda     #$60
	jsr     addeq0sp
	jsr     ldax0sp
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ palette_selection_handler (unsigned int mouse_x, unsigned int mouse_y, unsigned char mouse_buttons)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_palette_selection_handler: near

.segment	"CODE"

	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	ldy     #$F0
	jsr     decaxy
	jsr     pushax
	lda     $005A
	jsr     tosudiva0
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	ldy     #$60
	jsr     decaxy
	jsr     pushax
	lda     $005B
	jsr     tosudiva0
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     $0059
	jsr     tosumula0
	jsr     tosaddax
	jsr     pusha
	lda     _bmx_no_pals+1
	sta     ptr1+1
	lda     _bmx_no_pals
	sta     ptr1
	lda     (ptr1)
	cmp     (sp)
	bcc     L0004
	beq     L0004
	ldy     #$03
	lda     (sp),y
	and     #$01
	beq     L0003
	lda     #<(__primary_colour)
	ldx     #>(__primary_colour)
	bra     L0008
L0003:	lda     #<(__secondary_colour)
	ldx     #>(__secondary_colour)
L0008:	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     _set_colour
L0004:	jmp     incsp8

.endproc

