;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__write_history_byte
	.import		__add_history_node_position
	.import		__get_history_byte
	.import		__get_history_redo_byte
	.export		_add_history_node_position
	.export		_add_history_node_row
	.export		_add_new_history_node
	.export		_restore_last_history_node
	.export		_undo_last_history_node
	.import		_bmx_width
	.import		_bmx_height
	.import		__draw_row_to_sprite
	.import		__get_pixel
	.export		_node_start_pos1
	.export		_node_start_pos2
	.export		_starting_new_node
	.export		_last_x
	.export		_last_y
	.export		_length_counter
	.export		_curr_col

.segment	"DATA"

_node_start_pos1:
	.dword	$00000000
_node_start_pos2:
	.dword	$00000000
_starting_new_node:
	.byte	$01
_last_x:
	.byte	$00
_last_y:
	.byte	$00
_length_counter:
	.byte	$00

.segment	"BSS"

_curr_col:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ add_history_node_position (unsigned char x, unsigned char y, unsigned char colour)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_history_node_position: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     tosicmp
	jcs     L0006
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     ldaxi
	jsr     tosicmp
	bcs     L0006
	lda     _last_x
	ldy     #$02
	cmp     (sp),y
	bne     L000B
	lda     _last_y
	dey
	cmp     (sp),y
	beq     L0006
L000B:	lda     _length_counter
	cmp     #$FF
	bne     L0009
	jsr     _add_new_history_node
L0009:	lda     _starting_new_node
	beq     L000A
	lda     (sp)
	sta     _curr_col
	lda     $0056+3
	sta     _node_start_pos1+3
	lda     $0056+2
	sta     _node_start_pos1+2
	ldx     $0056+1
	lda     $0056
	sta     _node_start_pos1
	stx     _node_start_pos1+1
	lda     #$00
	stz     _starting_new_node
	jsr     __write_history_byte
	lda     $0056+3
	sta     _node_start_pos2+3
	lda     $0056+2
	sta     _node_start_pos2+2
	ldx     $0056+1
	lda     $0056
	sta     _node_start_pos2
	stx     _node_start_pos2+1
	lda     #$00
	jsr     __write_history_byte
	stz     _length_counter
L000A:	ldy     #$02
	lda     (sp),y
	sta     _last_x
	dey
	lda     (sp),y
	sta     _last_y
	inc     _length_counter
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     __add_history_node_position
L0006:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ add_history_node_row (unsigned char width, unsigned char x, unsigned char y, unsigned char colour)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_history_node_row: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$04
	lda     (sp),y
	jsr     __write_history_byte
	ldy     #$03
	lda     (sp),y
	jsr     __write_history_byte
	ldy     #$02
	lda     (sp),y
	jsr     __write_history_byte
	ldy     #$01
	lda     (sp),y
	jsr     __write_history_byte
	lda     #$00
L0007:	sta     (sp)
	ldy     #$04
	cmp     (sp),y
	bcs     L0003
	lda     (sp)
	clc
	dey
	adc     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     __get_pixel
	jsr     pusha
	lda     (sp)
	jsr     __write_history_byte
	jsr     incsp1
	clc
	lda     #$01
	adc     (sp)
	bra     L0007
L0003:	ldy     #$02
	lda     (sp),y
	jsr     __write_history_byte
	ldy     #$03
	lda     (sp),y
	jsr     __write_history_byte
	ldy     #$04
	lda     (sp),y
	jsr     __write_history_byte
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ add_new_history_node (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_new_history_node: near

.segment	"CODE"

	lda     #$80
	jmp     __write_history_byte

.endproc

; ---------------------------------------------------------------
; void __near__ restore_last_history_node (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_restore_last_history_node: near

.segment	"CODE"

	lda     $0056+3
	sta     sreg+1
	lda     $0056+2
	sta     sreg
	ldx     $0056+1
	lda     $0056
	jsr     pusheax
	lda     _node_start_pos1+3
	sta     sreg+1
	lda     _node_start_pos1+2
	sta     sreg
	ldx     _node_start_pos1+1
	lda     _node_start_pos1
	jsr     tosuleeax
	beq     L0002
	jsr     __get_history_redo_byte
	jsr     pusha
	jsr     __get_history_redo_byte
	jsr     pusha
	jsr     decsp1
	lda     #$00
L0007:	sta     (sp)
	ldy     #$02
	cmp     (sp),y
	bcs     L0004
	jsr     __get_history_redo_byte
	jsr     pusha
	jsr     __get_history_redo_byte
	jsr     pusha
	jsr     __get_history_redo_byte
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     __draw_row_to_sprite
	jsr     incsp3
	clc
	lda     #$01
	adc     (sp)
	bra     L0007
L0004:	jsr     __get_history_redo_byte
	jmp     incsp3
L0002:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ undo_last_history_node (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_undo_last_history_node: near

.segment	"CODE"

	lda     $0056+3
	sta     sreg+1
	lda     $0056+2
	sta     sreg
	ldx     $0056+1
	lda     $0056
	cmp     #$01
	txa
	sbc     #$A0
	lda     sreg
	sbc     #$04
	lda     sreg+1
	sbc     #$00
	bcc     L0002
	lda     #$00
	jsr     pusha
	jsr     __get_history_byte
	jsr     pusha
	lda     #$00
	ldy     #$01
L0007:	sta     (sp),y
	cmp     (sp)
	bcs     L0004
	jsr     __get_history_byte
	jsr     pusha
	jsr     __get_history_byte
	jsr     pusha
	jsr     __get_history_byte
	jsr     pusha
	lda     (sp)
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     __draw_row_to_sprite
	jsr     incsp3
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L0007
L0004:	jsr     __get_history_byte
	jsr     __get_history_byte
	jmp     incsp2
L0002:	rts

.endproc

