;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cbm_open
	.import		_cbm_close
	.import		_cbm_read
	.import		__wait_for_nmi
	.import		__init_irq_handler
	.import		__init_screen_mode
	.import		_get_keycode
	.import		_keycode
	.import		__initialize_mouse
	.import		__get_mouse_input
	.import		_set_layer_config
	.import		_change_tool
	.import		__current_tool
	.import		_bmx_vera_bit_depth
	.import		_bmx_width
	.import		_bmx_height
	.import		_bmx_no_pals
	.import		__transfer_pal_to_vera
	.import		__transfer_sprite_to_vram
	.import		__init_canvas_vera_tiles
	.export		_handle_keyboard_input
	.import		__draw_row_to_sprite
	.import		__image_data_size
	.import		_canvas_zoom_handler
	.import		_restore_last_history_node
	.import		_undo_last_history_node
	.import		_tool_handler
	.export		_filename
	.export		_load_bmx_file
	.export		_save_bmx_file
	.export		_timer
	.export		_main

.segment	"DATA"

_filename:
	.byte	$44,$52,$49,$50,$5A,$45,$52,$4F,$2E,$42,$4D,$58,$00
_timer:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ handle_keyboard_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_handle_keyboard_input: near

.segment	"CODE"

	lda     _keycode
	beq     L00E4
	cmp     #$1A
	jeq     _undo_last_history_node
	cmp     #$19
	jeq     _restore_last_history_node
	cmp     #$49
	bne     L0108
	lda     #$04
	jmp     _change_tool
L0108:	lda     _keycode
	cmp     #$42
	bne     L0109
	lda     #$00
	jmp     _change_tool
L0109:	lda     _keycode
	cmp     #$53
	jeq     _save_bmx_file
L00E4:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ load_bmx_file (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_bmx_file: near

.segment	"CODE"

	ldx     #$40
	lda     #$01
	sta     sreg
	dea
	stz     sreg+1
	jsr     pusheax
	lda     #$02
	jsr     pusha
	lda     #$0F
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #<(_filename)
	ldx     #>(_filename)
	jsr     _cbm_open
	lda     #$0F
	jsr     pusha
	ldx     #$04
	lda     #$00
	jsr     pushax
	tax
	lda     #$20
	jsr     _cbm_read
	lda     #$01
	sta     $0000
	lda     _bmx_no_pals+1
	sta     ptr1+1
	lda     _bmx_no_pals
	sta     ptr1
	lda     (ptr1)
	beq     L0093
	lda     #$0F
	jsr     pusha
	ldx     #$A0
	lda     #$00
	jsr     pushax
	lda     _bmx_no_pals+1
	sta     ptr1+1
	lda     _bmx_no_pals
	sta     ptr1
	lda     (ptr1)
	ldx     #$00
	asl     a
	bcc     L010B
	inx
	bra     L010B
L0093:	lda     #$0F
	jsr     pusha
	ldx     #$A0
	lda     #$00
	jsr     pushax
	ldx     #$02
L010B:	jsr     _cbm_read
	jsr     __transfer_pal_to_vera
	lda     (sp)
	sta     $0000
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     pushw
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     ldaxi
	jsr     tosumulax
	jsr     pushax
	lda     #$03
	jsr     pusha0
	lda     _bmx_vera_bit_depth+1
	sta     ptr1+1
	lda     _bmx_vera_bit_depth
	sta     ptr1
	lda     (ptr1)
	jsr     tossuba0
	jsr     tosshrax
	sta     __image_data_size
	stx     __image_data_size+1
	bra     L00BF
L00AC:	lda     #$0F
	jsr     pusha
	ldx     #$A0
	lda     #$00
	jsr     pushax
	ldx     #$20
	jsr     _cbm_read
	ldx     #$20
	lda     #$00
	stz     sreg
	stz     sreg+1
	ldy     #$01
	jsr     laddeqysp
	clc
	lda     #$01
	adc     (sp)
	sta     (sp)
	sta     $0000
	lda     __image_data_size
	cmp     #$01
	lda     __image_data_size+1
	sbc     #$20
	bcc     L00AD
	lda     __image_data_size
	sec
	sbc     #$00
	sta     __image_data_size
	lda     __image_data_size+1
	sbc     #$20
	sta     __image_data_size+1
L00BF:	lda     __image_data_size
	cmp     #$01
	lda     __image_data_size+1
	sbc     #$20
	bcs     L00AC
L00AD:	lda     #$0F
	jsr     pusha
	ldx     #$A0
	lda     #$00
	jsr     pushax
	lda     __image_data_size
	ldx     __image_data_size+1
	jsr     _cbm_read
	lda     #$0F
	jsr     _cbm_close
	jsr     __transfer_sprite_to_vram
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ save_bmx_file (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_save_bmx_file: near

.segment	"CODE"

	lda     #$0F
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #<(_filename)
	ldx     #>(_filename)
	jsr     _cbm_open
	lda     #$0F
	jmp     _cbm_close

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     __init_irq_handler
	jsr     __init_screen_mode
	jsr     _set_layer_config
	jsr     __initialize_mouse
	jsr     __init_canvas_vera_tiles
	jsr     _load_bmx_file
	lda     #$00
	stz     __current_tool
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$08
	jsr     pusha
	jsr     __draw_row_to_sprite
	lda     #$00
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$10
	jsr     pusha
	jsr     __draw_row_to_sprite
L00FB:	jsr     __wait_for_nmi
	jsr     _canvas_zoom_handler
	jsr     __get_mouse_input
	jsr     _get_keycode
	jsr     _tool_handler
	bra     L00FB

.endproc

