;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__load_palette_from_file
	.import		__load_file_into_vram
	.import		__set_layer0_enable
	.import		__set_layer1_enable
	.import		__set_sprites_enable
	.import		__set_sprite_attribute
	.import		__current_tool
	.export		_original_tool
	.export		_tool_timer
	.export		_set_layer_config
	.export		_initialize_paint_ui
	.export		_change_tool
	.export		_header_container_id
	.export		_tool_container_id
	.export		_palette_container_id
	.export		_context_container_id
	.import		_create_ui_element
	.import		_init_text_element
	.import		_init_icon_element
	.import		__ui_type
	.import		__ui_size_x
	.import		__ui_size_y
	.import		__ui_palette
	.import		__ui_rend_func_low
	.import		__ui_rend_func_high
	.import		__ui_first_child
	.import		__ui_next_sib
	.import		__draw_ui_element
	.import		__empty_draw_func
	.import		__draw_ui_text
	.import		__draw_ui_box
	.import		__draw_ui_icon
	.import		__press_toggle_button_mouse_func
	.export		_tileset0_addr
	.export		_tileset1_addr
	.export		_tilemap0_addr
	.export		_tilemap1_addr
	.export		_pal_text
	.export		_initialize_palette_ui
	.export		_tool_text
	.export		_initialize_tool_ui

.segment	"DATA"

_tileset0_addr:
	.dword	$00000000
_tileset1_addr:
	.dword	$00000000
_tilemap0_addr:
	.dword	$00010000
_tilemap1_addr:
	.dword	$00012000
_pal_text:
	.byte	$2D,$50,$41,$4C,$45,$54,$54,$45,$00
_original_tool:
	.byte	$00
_tool_timer:
	.byte	$00
_tool_text:
	.byte	$2D,$54,$4F,$4F,$4C,$53,$00

.segment	"RODATA"

S0004:
	.byte	$44,$30,$50,$41,$4C,$53,$45,$4C,$2E,$53,$50,$52,$00
S0005:
	.byte	$44,$30,$4D,$4F,$55,$53,$45,$2E,$53,$50,$52,$00
S0003:
	.byte	$44,$30,$46,$4F,$4E,$54,$2E,$53,$50,$52,$00
S0006:
	.byte	$46,$4F,$4E,$54,$2E,$50,$41,$4C,$00

.segment	"BSS"

_header_container_id:
	.res	1,$00
_tool_container_id:
	.res	1,$00
_palette_container_id:
	.res	1,$00
_context_container_id:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ set_layer_config (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_layer_config: near

.segment	"CODE"

	lda     #$01
	jsr     __set_layer0_enable
	lda     #$00
	jsr     __set_layer1_enable
	lda     #$01
	jsr     __set_sprites_enable
	lda     #$40
	sta     $9F2A
	sta     $9F2B
	stz     $9F30
	stz     $9F30+1
	stz     $9F32
	stz     $9F32+1
	lda     #$21
	sta     $9F2D
	lda     _tilemap0_addr+3
	sta     sreg+1
	lda     _tilemap0_addr+2
	sta     sreg
	lda     _tilemap0_addr+1
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	stz     sreg+1
	jsr     shreax1
	sta     $9F2E
	lda     _tileset0_addr+3
	sta     sreg+1
	lda     _tileset0_addr+2
	sta     sreg
	lda     _tileset0_addr+1
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	stz     sreg+1
	jsr     shreax1
	and     #$FC
	sta     $9F2F
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ initialize_paint_ui (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initialize_paint_ui: near

.segment	"CODE"

	lda     #$02
	sta     __ui_type
	lda     #$50
	sta     __ui_size_x
	lda     #$3C
	sta     __ui_size_y
	lda     #<(__empty_draw_func)
	sta     __ui_rend_func_low
	ldx     #>(__empty_draw_func)
	stx     __ui_rend_func_high
	cpx     #$80
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	lda     #$0A
	jsr     pusha
	lda     #$00
	jsr     pusha
	tax
	jsr     __load_file_into_vram
	lda     #<(S0004)
	ldx     #>(S0004)
	jsr     pushax
	lda     #$0D
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldx     #$65
	dea
	jsr     __load_file_into_vram
	lda     #<(S0005)
	ldx     #>(S0005)
	jsr     pushax
	lda     #$0C
	jsr     pusha
	lda     #$01
	jsr     pusha
	ldx     #$60
	dea
	jsr     __load_file_into_vram
	lda     #<(S0006)
	ldx     #>(S0006)
	jsr     pushax
	lda     #$09
	jsr     pusha
	lda     #$0E
	jsr     __load_palette_from_file
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     pusha
	lda     #$28
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(__draw_ui_box)
	ldx     #>(__draw_ui_box)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	sta     _header_container_id
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$1C
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #<(__draw_ui_box)
	ldx     #>(__draw_ui_box)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	sta     _tool_container_id
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$1C
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$14
	jsr     pusha
	lda     #<(__draw_ui_box)
	ldx     #>(__draw_ui_box)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	sta     _palette_container_id
	lda     #$00
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$17
	jsr     pusha
	lda     #$1C
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #<(__draw_ui_box)
	ldx     #>(__draw_ui_box)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	sta     _context_container_id
	jsr     _initialize_palette_ui
	lda     #$07
	jsr     pusha
	ldx     #$0A
	lda     #$00
	jsr     pushax
	ina
	jsr     pusha
	lda     #$F0
	jsr     pusha0
	lda     #$60
	jsr     pusha0
	lda     #$0C
	jsr     pusha
	lda     #$0F
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	lda     #$08
	jsr     pusha
	ldx     #$0A
	lda     #$80
	jsr     pushax
	lda     #$01
	jsr     pusha
	lda     #$F0
	jsr     pusha0
	lda     #$A0
	jsr     pusha0
	lda     #$0C
	jsr     pusha
	lda     #$0F
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	jmp     _initialize_tool_ui

.endproc

; ---------------------------------------------------------------
; void __near__ change_tool (unsigned char new_tool)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_change_tool: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$02
	lda     (sp),y
	sta     __current_tool
	ldy     _tool_container_id
	lda     __ui_first_child,y
	sta     (sp)
	lda     #$00
	ldy     #$01
L000E:	sta     (sp),y
	cmp     #$09
	bcs     L000F
	lda     (sp),y
	jsr     pusha0
	lda     __current_tool
	ina
	bne     L0008
	ldx     #$01
L0008:	jsr     tosicmp
	bne     L0007
	lda     (sp)
	tay
	lda     #$E0
	bra     L000D
L0007:	lda     (sp)
	tay
	lda     #$F0
L000D:	sta     __ui_palette,y
	lda     (sp)
	tay
	lda     __ui_next_sib,y
	sta     (sp)
	ldy     #$01
	clc
	tya
	adc     (sp),y
	bra     L000E
L000F:	lda     _tool_container_id
	jsr     __draw_ui_element
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; int __near__ initialize_palette_ui (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initialize_palette_ui: near

.segment	"CODE"

	lda     _palette_container_id
	jsr     pusha
	lda     #$01
	jsr     pusha
	ina
	jsr     pusha
	dea
	jsr     pusha
	dea
	jsr     pusha
	ina
	jsr     pusha
	lda     #<(__draw_ui_text)
	ldx     #>(__draw_ui_text)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	jsr     pusha
	lda     (sp)
	jsr     pusha
	lda     #<(_pal_text)
	ldx     #>(_pal_text)
	jsr     _init_text_element
	ldx     #$00
	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; int __near__ initialize_tool_ui (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initialize_tool_ui: near

.segment	"CODE"

	jsr     decsp1
	lda     #$02
	jsr     pusha
	jsr     pusha
	jsr     decsp1
	lda     #$00
	jsr     pusha
	lda     _tool_container_id
	jsr     pusha
	lda     #$01
	jsr     pusha
	ina
	jsr     pusha
	dea
	jsr     pusha
	dea
	jsr     pusha
	ina
	jsr     pusha
	lda     #<(__draw_ui_text)
	ldx     #>(__draw_ui_text)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	jsr     pusha
	lda     (sp)
	jsr     pusha
	lda     #<(_tool_text)
	ldx     #>(_tool_text)
	jsr     _init_text_element
	lda     #$00
	ldy     #$05
L0009:	sta     (sp),y
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jcs     L000C
	lda     _tool_container_id
	jsr     pusha
	lda     #$06
	jsr     pusha
	tay
	lda     (sp),y
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     pusha
	lda     #$02
	jsr     pusha
	jsr     pusha
	lda     #<(__draw_ui_icon)
	ldx     #>(__draw_ui_icon)
	jsr     pushax
	lda     #<(__press_toggle_button_mouse_func)
	ldx     #>(__press_toggle_button_mouse_func)
	jsr     _create_ui_element
	ldy     #$02
	sta     (sp),y
	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$60
	jsr     incaxy
	jsr     pusha
	lda     #<(__current_tool)
	ldx     #>(__current_tool)
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	jsr     _init_icon_element
	ldy     #$04
	clc
	lda     #$02
	adc     (sp),y
	sta     (sp),y
	iny
	lda     (sp),y
	bne     L0006
	ldy     #$02
	lda     (sp),y
	tay
	lda     #$E0
	sta     __ui_palette,y
L0006:	ldy     #$01
	clc
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	cmp     #$03
	bne     L000B
	dea
	dey
	sta     (sp),y
	dey
	clc
	adc     (sp),y
	sta     (sp),y
	ldy     #$05
L000B:	clc
	lda     #$01
	adc     (sp),y
	jmp     L0009
L000C:	txa
	jmp     incsp6

.endproc

