;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		__set_sprite_attribute
	.export		_bmx_header
	.export		_bmx_bit_depth
	.export		_bmx_vera_bit_depth
	.export		_bmx_width
	.export		_bmx_height
	.export		_bmx_no_pals
	.export		_bmx_pal_start
	.export		_bmx_data_start
	.import		__x_axis
	.import		__y_axis
	.import		__canvas_scale
	.import		__canvas_pow_scale
	.import		__canvas_paint_offset
	.import		__canvas_paint_width
	.import		__display_width
	.import		__display_height
	.import		__sprite_vram_size
	.import		__sprite_size
	.import		__display_row_pow
	.import		__display_has_columns
	.export		_init_canvas_vera_sprites
	.export		_canvas_zoom_handler
	.import		_keycode
	.export		_x_axis
	.export		_y_axis
	.export		_scale
	.export		_get_axis_scale
	.export		_zoom
	.export		_x_pan
	.export		_y_pan

.segment	"DATA"

_bmx_header:
	.word	$0400
_bmx_bit_depth:
	.word	$0404
_bmx_vera_bit_depth:
	.word	$0405
_bmx_width:
	.word	$0406
_bmx_height:
	.word	$0408
_bmx_no_pals:
	.word	$040A
_bmx_pal_start:
	.word	$040B
_bmx_data_start:
	.word	$040C
_x_axis:
	.byte	$00
_y_axis:
	.byte	$00
_scale:
	.byte	$00
_zoom:
	.byte	$04
_x_pan:
	.word	$0000
_y_pan:
	.word	$0000

; ---------------------------------------------------------------
; void __near__ init_canvas_vera_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_canvas_vera_sprites: near

.segment	"CODE"

	ldx     #$06
	lda     #$00
	jsr     pushax
	jsr     pusha
	stz     __canvas_scale
	stz     __canvas_pow_scale
	stz     __canvas_paint_offset
	stz     __display_has_columns
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     _get_axis_scale
	sta     __x_axis
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     ldaxi
	jsr     _get_axis_scale
	sta     __y_axis
	sta     __canvas_pow_scale
	lda     __x_axis
	cmp     __canvas_pow_scale
	bcc     L004C
	sta     __canvas_pow_scale
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     shrax1
	sta     __canvas_paint_offset
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     shrax1
	bra     L010B
L004C:	lda     _bmx_width+1
	sta     ptr1+1
	lda     _bmx_width
	sta     ptr1
	lda     (ptr1)
L010B:	sta     __canvas_paint_width
	ldx     #$00
	lda     #$04
	sec
	sbc     __canvas_pow_scale
	sta     __canvas_scale
	tay
	lda     #$01
	jsr     aslaxy
	sta     __canvas_scale
	lda     __y_axis
	cmp     __x_axis
	bne     L010C
	ldx     #$10
	stz     __sprite_size
	stx     __sprite_size+1
	lda     #$0F
	sta     (sp)
	lda     #$04
	sec
	sbc     __canvas_pow_scale
	clc
	adc     #$06
	sta     __display_row_pow
	jmp     L008B
L010C:	lda     __x_axis
	cmp     __y_axis
	jcs     L0113
	lda     __canvas_scale
	jsr     pusha0
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     ldaxi
	jsr     tosumulax
	jsr     pusha
	ldx     #$00
	lda     (sp)
	jsr     shlax4
	jsr     shlax2
	sta     __sprite_size
	stx     __sprite_size+1
	lda     #$0C
	ldy     #$01
	sta     (sp),y
	lda     #$04
	sec
	sbc     __canvas_pow_scale
	sta     __display_row_pow
	lda     (sp)
	cmp     #$08
	bne     L010E
	lda     #$03
	clc
	adc     __display_row_pow
	sta     __display_row_pow
L010E:	lda     (sp)
	cmp     #$10
	bne     L0110
	ldy     #$01
	lda     (sp),y
	ora     #$01
	sta     (sp),y
	lda     #$04
	clc
	adc     __display_row_pow
	sta     __display_row_pow
L0110:	lda     (sp)
	cmp     #$20
	bne     L0112
	ldy     #$01
	lda     (sp),y
	ora     #$02
	sta     (sp),y
	lda     #$05
	clc
	adc     __display_row_pow
	sta     __display_row_pow
L0112:	lda     (sp)
	cmp     #$40
	bne     L009F
	ldy     #$01
	lda     (sp),y
	ora     #$03
	sta     (sp),y
	lda     #$06
	clc
	adc     __display_row_pow
	sta     __display_row_pow
	bra     L009F
L0113:	lda     __canvas_scale
	jsr     pusha0
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     ldaxi
	jsr     tosumulax
	jsr     pusha
	ldx     #$00
	lda     (sp)
	jsr     shlax4
	jsr     shlax2
	sta     __sprite_size
	stx     __sprite_size+1
	lda     #$03
	ldy     #$01
	sta     (sp),y
	ina
	sec
	sbc     __canvas_pow_scale
	clc
	adc     #$06
	sta     __display_row_pow
	lda     (sp)
	cmp     #$10
	bne     L0115
	ldy     #$01
	lda     (sp),y
	ora     #$04
	sta     (sp),y
L0115:	lda     (sp)
	cmp     #$20
	bne     L0117
	ldy     #$01
	lda     (sp),y
	ora     #$08
	sta     (sp),y
L0117:	lda     (sp)
	cmp     #$40
	bne     L009F
	ldy     #$01
	lda     (sp),y
	ora     #$0C
	sta     (sp),y
L009F:	jsr     incsp1
L008B:	lda     __sprite_size
	ldx     __sprite_size+1
	jsr     shrax4
	jsr     shrax1
	sta     __sprite_vram_size
	stx     __sprite_vram_size+1
	lda     #$03
	clc
	adc     __x_axis
	sta     __x_axis
	lda     #$03
	clc
	adc     __y_axis
	sta     __y_axis
	lda     _bmx_width
	ldx     _bmx_width+1
	jsr     pushw
	lda     __canvas_scale
	jsr     tosumula0
	sta     __display_width
	lda     _bmx_height
	ldx     _bmx_height+1
	jsr     pushw
	lda     __canvas_scale
	jsr     tosumula0
	sta     __display_height
	lda     #$01
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	lda     #$60
	jsr     pusha0
	lda     #$28
	jsr     pusha0
	lda     #$04
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	lda     __sprite_vram_size
	ldx     __sprite_vram_size+1
	ldy     #$01
	jsr     addeqysp
	lda     __x_axis
	sec
	sbc     __y_axis
	sta     tmp1
	lda     tmp1
	beq     L010A
	bcs     L0118
L010A:	lda     #$02
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	lda     #$60
	jsr     pusha0
	lda     #$68
	jsr     pusha0
	lda     #$04
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	lda     __sprite_vram_size
	ldx     __sprite_vram_size+1
	ldy     #$01
	jsr     addeqysp
	lda     #$FF
	sta     __display_has_columns
L0118:	lda     __canvas_paint_offset
	beq     L00D6
	lda     #$03
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	lda     #$A0
	jsr     pusha0
	lda     #$28
	jsr     pusha0
	lda     #$04
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	lda     __sprite_vram_size
	ldx     __sprite_vram_size+1
	ldy     #$01
	jsr     addeqysp
	lda     __display_has_columns
	beq     L00D6
	lda     #$04
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	lda     #$01
	jsr     pusha
	lda     #$A0
	jsr     pusha0
	lda     #$68
	jsr     pusha0
	lda     #$04
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	lda     #$00
	jsr     __set_sprite_attribute
	lda     __sprite_vram_size
	ldx     __sprite_vram_size+1
	ldy     #$01
	jsr     addeqysp
L00D6:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ canvas_zoom_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_canvas_zoom_handler: near

.segment	"CODE"

	lda     _keycode
	beq     L011C
	lda     _keycode
	cmp     #$1D
	bne     L0119
	inc     _x_pan
	bne     L0119
	inc     _x_pan+1
L0119:	lda     _keycode
	cmp     #$9D
	bne     L011A
	lda     _x_pan
	sec
	sbc     #$01
	sta     _x_pan
	bcs     L011A
	dec     _x_pan+1
L011A:	lda     _keycode
	cmp     #$11
	bne     L011B
	inc     _y_pan
	bne     L011B
	inc     _y_pan+1
L011B:	lda     _keycode
	cmp     #$91
	bne     L011C
	lda     _y_pan
	sec
	sbc     #$01
	sta     _y_pan
	bcs     L011C
	dec     _y_pan+1
L011C:	lda     #$80
	jsr     pusha0
	lda     _zoom
	jsr     tosudiva0
	sta     $9F2A
	lda     #$80
	jsr     pusha0
	lda     _zoom
	jsr     tosudiva0
	sta     $9F2B
	lda     _x_pan+1
	sta     $9F30+1
	lda     _x_pan
	sta     $9F30
	lda     _y_pan+1
	sta     $9F32+1
	lda     _y_pan
	sta     $9F32
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ get_axis_scale (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_axis_scale: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     shrax4
	bra     L011E
L002E:	clc
	lda     #$01
	adc     (sp)
	sta     (sp)
	ldy     #$02
	jsr     ldaxysp
	jsr     shrax1
L011E:	ldy     #$01
	jsr     staxysp
	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L002E
	tax
	lda     (sp)
	jmp     incsp3

.endproc

